# name: CI

# on:
#     push:
#         branches: [main, development]
#     pull_request:
#         branches: [main, development]

# jobs:
#     build:
#         strategy:
#             matrix:
#                 os: [ubuntu-latest]
#                 node: [20.x]
#         runs-on: ${{ matrix.os }}

#         steps:
#             - name: Setup Node.js environment
#               uses: actions/setup-node@v1
#               with:
#                   node-version: ${{ matrix.node }}

#             - name: Checkout branch
#               uses: actions/checkout@v2

#             - name: Install dependencies
#               run: npm install

#             - name: Run ESLint Typescript
#               run: npm run lint:ts

#             - name: Run ESLint SCSS
#               run: npm run lint:scss

#             - name: Run unit tests
#               run: npm run test:unit

#             - name: Build Storybook
#               run: npm run storybook:build

#             - name: Run UI tests
#               run: npm run test:ui:ci

#             - name: Build production project
#               run: npm run build:prod
name: CI

on:
    push:
        branches: [main, development]
    pull_request:
        branches: [main, development]
permissions:
    contents: write
    pages: write
    id-token: write
concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    build-and-ui-testing:
        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [20.x]
        runs-on: ${{ matrix.os }}
        concurrency: ci-${{ github.ref }}
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Setup Node.js environment
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: Checkout branch
              uses: actions/checkout@v2

            - name: Install dependencies
              run: npm ci

            - name: Build production project
              run: npm run build:prod

            - name: Build Storybook
              run: npm run storybook:build

            - name: Run UI tests
              run: npm run test:ui:ci

            - name: Generate HTML report
              run: npm run test:ui:report

            - name: Setup Pages
              uses: actions/configure-pages@v3

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v1
              with:
                  path: '.loki'

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v1

    checks:
        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [20.x]
        runs-on: ${{ matrix.os }}

        steps:
            - name: Setup Node.js environment
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: Checkout branch
              uses: actions/checkout@v2

            - name: Install dependencies
              run: npm ci

            - name: Run ESLint Typescript
              run: npm run lint:ts

            - name: Run ESLint SCSS
              run: npm run lint:scss

            - name: Run unit tests
              run: npm run test:unit
